version: '3.8'
services:
  bookdb:
    container_name: bookdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - bookdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password123*
      - POSTGRES_DB=bookdb
  moviedb:
    container_name: moviedb
    restart: always
    ports: 
      - "27018:27017"
    volumes:
      - moviedb_volume:/data/db
  bookapi:
    container_name: bookapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Devolopment
      - "ConnectionStrings:PostgreSQL=User ID=sa;Password=Password123*;Host=bookdb;Port=5432;Database=bookdb;"
    ports:
      - "5011:80"
    depends_on:
      - bookdb
  movieapi:
    container_name: movieapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Devolopment
      - "MongoDbSettings:ConnectionString=mongodb://moviedb:27017"
    ports:
      - "5012:80"
    depends_on:
      - moviedb
  gatewayapi:
    container_name: gatewayapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"